// 英単語確認アプリ 単語データ
// 各例文から重要な英単語・熟語を抽出。words: [英単語, 日本語の意味] の配列。
// en / ja は例文（正解表示時に提示）。

const SENTENCES = [
  { id: 1, en: `That cute reporter is from Canada.`, ja: `あのかわいいレポーターは、カナダ出身だ。`, words: [["that", "あの"], ["cute", "かわいい"], ["reporter", "レポーター・記者"], ["from", "～から・出身"], ["Canada", "カナダ"]] },
  { id: 2, en: `Sightseeing in Kyoto is expensive.`, ja: `京都の観光費用は高い。`, words: [["sightseeing", "観光"], ["Kyoto", "京都"], ["expensive", "高価な・値段が高い"], ["in", "～の中で・～で"]] },
  { id: 3, en: `Sometimes we cook food together.`, ja: `ときどき、私たちはいっしょに料理をする。`, words: [["sometimes", "ときどき"], ["we", "私たち"], ["cook", "料理する"], ["food", "食べ物"], ["together", "いっしょに"]] },
  { id: 4, en: `We had tea and cake in the hotel.`, ja: `私たちは、ホテルでお茶とケーキをいただいた。`, words: [["had", "食べた・持っていた"], ["tea", "お茶"], ["cake", "ケーキ"], ["hotel", "ホテル"], ["and", "～と・そして"]] },
  { id: 5, en: `I saw a beautiful woman among the trees.`, ja: `私は木々の中で、美しい女性を見た。`, words: [["saw", "見た（seeの過去形）"], ["beautiful", "美しい"], ["woman", "女性"], ["among", "～の間に"], ["trees", "木々"]] },
  { id: 6, en: `Did you buy those blue clothes at that shop?`, ja: `あのお店で、あれらの青い服を買ったのですか?`, words: [["buy", "買う"], ["those", "あれらの"], ["blue", "青い"], ["clothes", "服"], ["shop", "店"], ["you", "あなた"], ["that", "あの・その"]] },
  { id: 7, en: `Yesterday, I drove a car for the first time.`, ja: `昨日、私は初めて車を運転した。`, words: [["yesterday", "昨日"], ["drove", "運転した（driveの過去形）"], ["car", "車"], ["for the first time", "初めて"]] },
  { id: 8, en: `Mary caught three small fish at the lake.`, ja: `メアリーは、湖で3匹の小さい魚を捕まえた。`, words: [["caught", "捕まえた（catchの過去形）"], ["three", "3つの"], ["small", "小さい"], ["fish", "魚"], ["lake", "湖"]] },
  { id: 9, en: `Did you hear our club's plan for summer vacation?`, ja: `夏休みのクラブの計画を聞きましたか？`, words: [["hear", "聞く"], ["our", "私たちの"], ["club", "クラブ"], ["plan", "計画"], ["summer", "夏"], ["vacation", "休暇"]] },
  { id: 10, en: `He always listens to classical music at night.`, ja: `彼はいつも、夜にクラシック音楽を聞きます。`, words: [["always", "いつも"], ["listen to", "～を聞く"], ["classical", "クラシックの・古典的な"], ["music", "音楽"], ["at night", "夜に"]] },
  { id: 11, en: `Everyone knows the famous astronaut.`, ja: `すべての人が、その有名な宇宙飛行士を知っている。`, words: [["everyone", "すべての人"], ["know", "知っている"], ["famous", "有名な"], ["astronaut", "宇宙飛行士"]] },
  { id: 12, en: `My sister bought only four flowers at the market.`, ja: `妹［姉］は、市場で４本だけ花を買いました。`, words: [["my", "私の"], ["sister", "妹・姉"], ["bought", "買った（buyの過去形）"], ["only", "～だけ"], ["flowers", "花"], ["market", "市場"]] },
  { id: 13, en: `The pond of the temple is about 10 feet deep.`, ja: `その寺の池は、約１０フィートの深さである。`, words: [["pond", "池"], ["temple", "寺"], ["about", "約"], ["feet", "フィート（footの複数形）"], ["deep", "深い"]] },
  { id: 14, en: `Can I sit next to you?`, ja: `あなたの隣に座っていいですか?`, words: [["sit", "座る"], ["next to", "～の隣に"], ["Can I ~?", "～してもいいですか"], ["you", "あなた"]] },
  { id: 15, en: `I share a desk and computer with my brother.`, ja: `私は兄［弟］と、机とコンピューターを共有している。`, words: [["share", "共有する"], ["desk", "机"], ["computer", "コンピューター"], ["with", "～と・～で"], ["brother", "兄・弟"]] },
  { id: 16, en: `Someone is walking quickly across the street.`, ja: `だれかが、素早くその通りを横切って歩いている。`, words: [["someone", "だれか"], ["walk", "歩く"], ["quickly", "素早く"], ["across", "～を横切って"], ["street", "通り"]] },
  { id: 17, en: `Millions of soccer fans watched the special match on TV.`, ja: `何百万ものサッカーファンが、テレビでその特別試合を見た。`, words: [["millions of", "何百万もの"], ["soccer", "サッカー"], ["fans", "ファン"], ["watch", "見る"], ["special", "特別な"], ["match", "試合"]] },
  { id: 18, en: `I agree with your wonderful idea.`, ja: `私は、あなたのすばらしいアイディアに賛成です。`, words: [["agree with", "～に賛成する"], ["your", "あなたの"], ["wonderful", "すばらしい"], ["idea", "アイディア"]] },
  { id: 19, en: `He repaired the roof in windy weather.`, ja: `彼は風の強い天気の中、屋根を修理した。`, words: [["repaired", "修理した"], ["roof", "屋根"], ["windy", "風の強い"], ["weather", "天気"]] },
  { id: 20, en: `My mom and I went to the restaurant behind the junior high school.`, ja: `お母さんと私は、私の中学校の後ろにあるレストランに行った。`, words: [["mom", "お母さん"], ["went", "行った（goの過去形）"], ["restaurant", "レストラン"], ["behind", "～の後ろに"], ["junior high school", "中学校"]] },
  { id: 21, en: `The pretty girl went on a trip to Singapore two years ago.`, ja: `そのかわいい女の子は、２年前にシンガポールに旅行に行きました。`, words: [["pretty", "かわいい"], ["girl", "女の子"], ["go on a trip", "旅行に行く"], ["Singapore", "シンガポール"], ["two years ago", "2年前"]] },
  { id: 22, en: `At last, he spoke slowly in English.`, ja: `ついに、彼は英語でゆっくりと話した。`, words: [["at last", "ついに"], ["spoke", "話した（speakの過去形）"], ["slowly", "ゆっくりと"], ["English", "英語"]] },
  { id: 23, en: `Because of the south wind, the large cloud is moving fast in the sky.`, ja: `南風のために、空で大きな雲が早く動いている。`, words: [["because of", "～のために"], ["south", "南の"], ["wind", "風"], ["large", "大きい"], ["cloud", "雲"], ["sky", "空"]] },
  { id: 24, en: `The rich woman paid a lot of money for the table.`, ja: `そのお金持ちの女性は、そのテーブルに多額のお金を払った。`, words: [["rich", "裕福な"], ["woman", "女性"], ["paid", "払った（payの過去形）"], ["a lot of", "たくさんの"], ["money", "お金"], ["table", "テーブル"]] },
  { id: 25, en: `I joined a treasure hunt every Sunday.`, ja: `私は、毎週日曜日に、宝探しに加わった。`, words: [["joined", "加わった"], ["treasure", "宝"], ["hunt", "探し・狩り"], ["every", "毎～・すべての"], ["Sunday", "日曜日"]] },
  { id: 26, en: `Table tennis is one of the popular sports in elementary school.`, ja: `卓球は、小学校で人気のあるスポーツのひとつである。`, words: [["table tennis", "卓球"], ["one of", "～の一つ"], ["popular", "人気のある"], ["sports", "スポーツ"], ["elementary school", "小学校"]] },
  { id: 27, en: `The national park is on the left side of the street.`, ja: `国立公園は道の左側にある。`, words: [["national", "国立の・国の"], ["park", "公園"], ["left", "左"], ["side", "側"], ["street", "通り"]] },
  { id: 28, en: `My brother chose his bicycle carefully.`, ja: `私の兄［弟］は、自転車を注意深く選んだ。`, words: [["chose", "選んだ（chooseの過去形）"], ["his", "彼の"], ["bicycle", "自転車"], ["carefully", "注意深く"]] },
  { id: 29, en: `The staff is waiting for the judge.`, ja: `職員は裁判官を待っている。`, words: [["staff", "職員"], ["wait for", "～を待つ"], ["judge", "裁判官"]] },
  { id: 30, en: `He is still walking through the crowd.`, ja: `彼は群衆の間をまだ歩いている。`, words: [["he", "彼"], ["still", "まだ"], ["walk", "歩く"], ["through", "～を通って"], ["crowd", "群衆"]] },
  { id: 31, en: `He cut his finger with a knife.`, ja: `彼はナイフで指を切った。`, words: [["cut", "切った"], ["his", "彼の"], ["finger", "指"], ["knife", "ナイフ"]] },
  { id: 32, en: `I have a meeting about the environment at noon.`, ja: `私は正午に、環境についての会議がある。`, words: [["have", "持つ・ある"], ["meeting", "会議"], ["environment", "環境"], ["noon", "正午"]] },
  { id: 33, en: `The car hit the front gate of our factory.`, ja: `その車は、私たちの工場の正門にぶつかった。`, words: [["hit", "ぶつかった・打つ"], ["front", "正面の・前の"], ["gate", "門"], ["factory", "工場"], ["our", "私たちの"], ["car", "車"]] },
  { id: 34, en: `Wet snow is falling now.`, ja: `湿った雪が、今降っている。`, words: [["wet", "湿った"], ["snow", "雪"], ["fall", "降る・落ちる"], ["now", "今"]] },
  { id: 35, en: `He is wearing a T-shirt, pants and shoes.`, ja: `彼はＴシャツとズボン、靴を履いている。`, words: [["he", "彼"], ["wear", "着ている"], ["T-shirt", "Tシャツ"], ["pants", "ズボン"], ["shoes", "靴"]] },
  { id: 36, en: `Actually, I am angry with you too.`, ja: `実際、私もあなたに怒っているんだよ。`, words: [["actually", "実際"], ["angry", "怒っている"], ["too", "～もまた"]] },
  { id: 37, en: `Please wrap this cup in soft paper.`, ja: `やわらかい紙で、このカップを包んでください。`, words: [["wrap", "包む"], ["this", "この・これ"], ["cup", "カップ"], ["soft", "やわらかい"], ["paper", "紙"]] },
  { id: 38, en: `Don't forget your cap and uniform for tonight's softball match.`, ja: `今晩のソフトボールの試合のために、帽子とユニフォームを忘れないでね。`, words: [["forget", "忘れる"], ["cap", "帽子"], ["uniform", "ユニフォーム"], ["tonight", "今晩"], ["softball", "ソフトボール"], ["match", "試合"]] },
  { id: 39, en: `Let's look up new words in the dictionary!`, ja: `辞書で新出語を調べよう！`, words: [["look up", "調べる"], ["new", "新しい"], ["words", "語・単語"], ["dictionary", "辞書"], ["let's", "～しよう"]] },
  { id: 40, en: `The 3Rs of reduce, reuse and recycle are popular in Germany.`, ja: `減らす、再使用する、再利用するの３Ｒは、ドイツでは一般的である。`, words: [["reduce", "減らす"], ["reuse", "再使用する"], ["recycle", "再利用する"], ["popular", "一般的な・人気のある"], ["Germany", "ドイツ"]] },
  { id: 41, en: `He laughed at funny stories from all over the world.`, ja: `彼は、世界中から集まったおもしろい話に笑った。`, words: [["laugh at", "～を笑う"], ["funny", "おもしろい"], ["stories", "話"], ["all over the world", "世界中"], ["he", "彼"]] },
  { id: 42, en: `That British guitar band produces a new album every year.`, ja: `あのイギリスのギターバンドは、毎年ニューアルバムを制作する。`, words: [["British", "イギリスの"], ["guitar", "ギター"], ["band", "バンド"], ["produce", "制作する"], ["album", "アルバム"], ["every year", "毎年"]] },
  { id: 43, en: `My grandma is famous for her warm heart.`, ja: `私のおばあちゃんは、温かい気持ちで有名である。`, words: [["grandma", "おばあちゃん"], ["be famous for", "～で有名"], ["warm", "温かい"], ["heart", "心・気持ち"]] },
  { id: 44, en: `He arrived at the library at nine o'clock in the morning.`, ja: `彼は朝の９時に図書館に着いた。`, words: [["arrive at", "～に着く"], ["library", "図書館"], ["in the morning", "朝に"], ["nine", "9の"], ["o'clock", "～時"], ["he", "彼"]] },
  { id: 45, en: `He is riding his bike at full speed.`, ja: `彼は最高速度で自転車に乗っている。`, words: [["ride", "乗る"], ["his", "彼の"], ["bike", "自転車"], ["full speed", "最高速度"]] },
  { id: 46, en: `I reported the situation to my teacher on the phone.`, ja: `私は状況を、先生に電話で報告した。`, words: [["reported", "報告した"], ["situation", "状況"], ["teacher", "先生"], ["on the phone", "電話で"]] },
  { id: 47, en: `You can easily connect this radio to the speaker.`, ja: `このラジオを、そのスピーカーに簡単につなげられます。`, words: [["easily", "簡単に"], ["connect", "つなげる"], ["this", "この・これ"], ["radio", "ラジオ"], ["speaker", "スピーカー"]] },
  { id: 48, en: `Where can I buy plastic garbage bags?`, ja: `どこでビニールのごみ袋を買うことができますか?`, words: [["plastic", "ビニールの・プラスチックの"], ["garbage", "ごみ"], ["bags", "袋"], ["where", "どこで"]] },
  { id: 49, en: `Thanks to you, we enjoyed a safe holiday.`, ja: `あなたのおかげで、私たちは安全な休日を楽しみました。`, words: [["thanks to", "～のおかげで"], ["enjoy", "楽しむ"], ["safe", "安全な"], ["holiday", "休日"], ["we", "私たち"]] },
  { id: 50, en: `The king is holding a gold plate in his hands.`, ja: `王は金色の皿を手に持っている。`, words: [["king", "王"], ["hold", "持つ"], ["gold", "金色の・金"], ["plate", "皿"], ["hands", "手"]] },
  { id: 51, en: `The number of members in our ski team is increasing every year.`, ja: `私たちのスキーチームのメンバーの数は、毎年増加している。`, words: [["the number of", "～の数"], ["members", "メンバー"], ["ski", "スキー"], ["team", "チーム"], ["increase", "増加する"]] },
  { id: 52, en: `A science fiction writer owns this bookstore.`, ja: `あるSF作家がこの書店を所有している。`, words: [["science fiction", "SF・空想科学"], ["writer", "作家"], ["own", "所有する"], ["this", "この・これ"], ["bookstore", "書店"]] },
  { id: 53, en: `We researched the difference between a supermarket and a convenience store.`, ja: `私たちはスーパーとコンビニの違いを調査した。`, words: [["researched", "調査した"], ["difference", "違い"], ["between", "～の間"], ["supermarket", "スーパー"], ["convenience store", "コンビニ"]] },
  { id: 54, en: `The clever man improved the design of the dining room.`, ja: `その頭の良い男性が、ダイニングルームのデザインを改善した。`, words: [["clever", "頭の良い"], ["man", "男・男性"], ["improve", "改善する"], ["design", "デザイン"], ["dining room", "ダイニングルーム"]] },
  { id: 55, en: `I saw a wild koala on my tour of Australia.`, ja: `私はオーストラリアの旅行中に、野生のコアラを見た。`, words: [["wild", "野生の"], ["koala", "コアラ"], ["tour", "旅行・ツアー"], ["Australia", "オーストラリア"], ["saw", "見た（seeの過去形）"]] },
  { id: 56, en: `"Whose notebook is this?" "It's mine."`, ja: `「これは誰のノートですか?」「私のです」`, words: [["whose", "誰の"], ["notebook", "ノート"], ["this", "これ・この"], ["mine", "私のもの"]] },
  { id: 57, en: `The architect has perfect knowledge of solar energy.`, ja: `その建築家は、太陽エネルギーの完全な知識を持っている。`, words: [["architect", "建築家"], ["perfect", "完全な"], ["knowledge", "知識"], ["solar energy", "太陽エネルギー"], ["have", "持つ"]] },
  { id: 58, en: `Is the branch office near the Olympic stadium?`, ja: `支社はオリンピックスタジアムのそばにあるのですか?`, words: [["branch office", "支社"], ["near", "～の近く"], ["Olympic", "オリンピックの"], ["stadium", "スタジアム"]] },
  { id: 59, en: `My husband called the bank clerk yesterday.`, ja: `夫は昨日、銀行員に電話をかけた。`, words: [["husband", "夫"], ["call", "電話をかける・呼ぶ"], ["bank", "銀行"], ["clerk", "店員・行員"], ["yesterday", "昨日"]] },
  { id: 60, en: `The TV drama is a bridge between Japan and Korea.`, ja: `そのテレビドラマは、日本と韓国とのかけ橋である。`, words: [["drama", "ドラマ"], ["bridge", "かけ橋"], ["between", "～の間"], ["Japan", "日本"], ["Korea", "韓国"]] },
  { id: 61, en: `The dog hid its bone under the seat.`, ja: `そのイヌは座席の下に骨を隠した。`, words: [["dog", "犬"], ["hid", "隠した（hideの過去形）"], ["bone", "骨"], ["under", "～の下"], ["seat", "座席"]] },
  { id: 62, en: `He took off his hat as a sign of respect.`, ja: `彼は尊敬の表れとして、帽子を脱いだ。`, words: [["take off", "脱ぐ"], ["hat", "帽子"], ["as a sign of", "～の表れとして"], ["respect", "尊敬"], ["he", "彼"]] },
  { id: 63, en: `The success of the performance depends on your everyday effort.`, ja: `その演奏の成功は、あなたの毎日の努力次第である。`, words: [["success", "成功"], ["performance", "演奏"], ["depend on", "～次第である"], ["everyday", "毎日の"], ["effort", "努力"]] },
  { id: 64, en: `The example is at the top of the page.`, ja: `その例はページの上部にあります。`, words: [["example", "例"], ["top", "上部"], ["page", "ページ"]] },
  { id: 65, en: `Some birds are flying over those high mountains.`, ja: `数羽の鳥があの高い山の上を飛んでいる。`, words: [["birds", "鳥"], ["fly", "飛ぶ"], ["over", "～の上を"], ["high", "高い"], ["mountains", "山"], ["some", "いくつかの・数羽の"], ["those", "あれらの"]] },
  { id: 66, en: `Many people get on the last bus.`, ja: `多くの人が最終のバスに乗る。`, words: [["many", "多くの"], ["people", "人々"], ["get on", "乗る"], ["last", "最終の"], ["bus", "バス"]] },
  { id: 67, en: `I get one hour of regular exercise on Wednesday.`, ja: `私は水曜日に１時間の定期的な運動をする。`, words: [["regular", "定期的な"], ["exercise", "運動"], ["Wednesday", "水曜日"]] },
  { id: 68, en: `The journalist searched for my e-mail address on the internet.`, ja: `そのジャーナリストは、インターネットで私のメールアドレスを探した。`, words: [["journalist", "ジャーナリスト"], ["search for", "～を探す"], ["e-mail address", "メールアドレス"], ["internet", "インターネット"]] },
  { id: 69, en: `Air pollution is a global problem these days.`, ja: `大気汚染はこのごろ、世界的な問題である。`, words: [["air pollution", "大気汚染"], ["global", "世界的な"], ["problem", "問題"], ["these days", "このごろ"]] },
  { id: 70, en: `Don't repeat the same mistake again.`, ja: `同じ間違いを再びくりかえすな。`, words: [["repeat", "くりかえす"], ["same", "同じ"], ["mistake", "間違い"], ["again", "再び"]] },
  { id: 71, en: `What is the capital of France?`, ja: `フランスの首都はどこですか？`, words: [["capital", "首都"], ["France", "フランス"]] },
  { id: 72, en: `Our leader removed many landmines with the army.`, ja: `私たちのリーダーは、軍隊とともに多くの地雷を除去した。`, words: [["leader", "リーダー"], ["removed", "除去した"], ["landmines", "地雷"], ["army", "軍隊"], ["our", "私たちの"], ["many", "多くの"]] },
  { id: 73, en: `The lion is a symbol of courage in our culture.`, ja: `ライオンは、私たちの文化では勇気の象徴である。`, words: [["lion", "ライオン"], ["symbol", "象徴"], ["courage", "勇気"], ["culture", "文化"]] },
  { id: 74, en: `I borrowed this comic from my aunt last week.`, ja: `私は先週、おばからこの漫画を借りた。`, words: [["borrowed", "借りた"], ["comic", "漫画"], ["aunt", "おば"], ["last week", "先週"], ["my", "私の"], ["I", "私"]] },
  { id: 75, en: `The tall woman was a famous basketball player in the United States.`, ja: `その背の高い女性は、アメリカで有名なバスケットボールの選手だった。`, words: [["tall", "背の高い"], ["famous", "有名な"], ["basketball", "バスケットボール"], ["player", "選手"], ["the United States", "アメリカ合衆国"]] },
  { id: 76, en: `In my experience, saving money is very important.`, ja: `私の経験では、お金を蓄えることはとても大切だ。`, words: [["experience", "経験"], ["save", "蓄える・節約する"], ["money", "お金"], ["important", "大切な"], ["very", "とても"], ["my", "私の"]] },
  { id: 77, en: `She is really tired of watching TV in her hospital bed.`, ja: `彼女は、病院のベッドでテレビを見ることに本当にうんざりしている。`, words: [["be tired of", "～にうんざりして"], ["watch", "見る"], ["hospital", "病院"]] },
  { id: 78, en: `That TV program is so interesting you should not miss it!`, ja: `あのテレビ番組はとてもおもしろいので、見逃すべきではないですよ！`, words: [["program", "番組"], ["so", "とても"], ["interesting", "おもしろい"], ["miss", "見逃す"], ["it", "それ"], ["TV", "テレビ"]] },
  { id: 79, en: `He has much more information than I do.`, ja: `彼は、私よりもずっと多くの情報を持っている。`, words: [["much more", "ずっと多くの"], ["information", "情報"], ["than", "～よりも"], ["he", "彼"], ["I", "私"]] },
  { id: 80, en: `Excuse us, but will you help me?`, ja: `すみません、手伝っていただけますか?`, words: [["excuse", "許す（excuse me＝すみません）"], ["help", "手伝う"], ["you", "あなた"], ["me", "私を"]] },
  { id: 81, en: `I will take care of your daughter this weekend.`, ja: `今週末、あなたの娘の世話をしましょう。`, words: [["take care of", "～の世話をする"], ["daughter", "娘"], ["weekend", "週末"], ["your", "あなたの"], ["will", "～するつもり"]] },
  { id: 82, en: `He discovered this plant while he was walking along the river.`, ja: `彼は川沿いを歩いているときに、この植物を発見した。`, words: [["discovered", "発見した"], ["plant", "植物"], ["while", "～の間"], ["along", "～に沿って"], ["river", "川"]] },
  { id: 83, en: `I want to live in a quiet place.`, ja: `私は静かな場所に住みたい。`, words: [["want to", "～したい"], ["live", "住む"], ["quiet", "静かな"], ["place", "場所"]] },
  { id: 84, en: `He needed to buy something to drink because he was so thirsty.`, ja: `彼は何か飲み物を買う必要があった。なぜなら彼はとてものどが渇いていたからだ。`, words: [["need", "必要とする"], ["something to drink", "何か飲み物"], ["so", "とても"], ["thirsty", "のどが渇いた"]] },
  { id: 85, en: `I want to talk to you about the new rule.`, ja: `私はあなたと、新しい規則について話をしたい。`, words: [["talk to", "～と話す"], ["about", "～について"], ["new", "新しい"], ["rule", "規則"]] },
  { id: 86, en: `How about going to the movies tonight?`, ja: `今晩、映画に行きませんか?`, words: [["how about", "～はどうですか"], ["go to the movies", "映画に行く"], ["tonight", "今晩"]] },
  { id: 87, en: `Because of the cold rain, the boy had to put on a coat.`, ja: `冷たい雨のために、その男の子はコートを着なければならなかった。`, words: [["because of", "～のために"], ["cold", "冷たい"], ["rain", "雨"], ["have to", "～しなければならない"], ["put on", "着る"], ["coat", "コート"]] },
  { id: 88, en: `Many fans cheered when the team won.`, ja: `そのチームが勝ったとき、多くのファンが喜んだ。`, words: [["fans", "ファン"], ["cheered", "喜んだ・応援した"], ["team", "チーム"], ["won", "勝った（winの過去形）"]] },
  { id: 89, en: `The boat with the powerful engine is going to sail to New York.`, ja: `力のあるエンジンを積んだ船は、ニューヨークに航海しようとしている。`, words: [["boat", "船・ボート"], ["powerful", "力のある"], ["engine", "エンジン"], ["be going to", "～しようとする"], ["sail", "航海する"], ["New York", "ニューヨーク"]] },
  { id: 90, en: `Next year, I wish to take an art course.`, ja: `来年、私は芸術の講座をとりたい。`, words: [["next year", "来年"], ["wish", "願う"], ["take", "とる・受ける"], ["art", "芸術"], ["course", "講座"]] },
  { id: 91, en: `He started to draw a strange picture in the garden.`, ja: `彼は庭で、奇妙な絵を描き始めた。`, words: [["start to", "～し始める"], ["draw", "描く"], ["strange", "奇妙な"], ["picture", "絵"], ["garden", "庭"]] },
  { id: 92, en: `I think my parents love each other.`, ja: `両親はお互いに愛し合っていると思う。`, words: [["think", "思う"], ["parents", "両親"], ["love", "愛する"], ["each other", "お互いに"]] },
  { id: 93, en: `I'm sure that you will understand the true reason later.`, ja: `あなたは本当の理由をあとで理解できると、私は確信しています。`, words: [["sure", "確信して"], ["understand", "理解する"], ["true", "本当の"], ["reason", "理由"], ["later", "あとで"]] },
  { id: 94, en: `Ten eggs are sold at five dollars.`, ja: `10個の卵が5ドルで売られている。`, words: [["eggs", "卵"], ["sold", "売られた（sellの過去分詞）"], ["dollars", "ドル"], ["ten", "10の"], ["five", "5の"]] },
  { id: 95, en: `There is nothing wrong with his actions.`, ja: `彼の行動には、何も間違ったところはない。`, words: [["nothing", "何も～ない"], ["wrong", "間違った"], ["actions", "行動"]] },
  { id: 96, en: `I will grow rice from April.`, ja: `私は4月から米を栽培します。`, words: [["grow", "栽培する・育てる"], ["rice", "米"], ["April", "4月"], ["I", "私"], ["will", "～するつもり"]] },
  { id: 97, en: `At first, I tried to follow my instructor.`, ja: `最初は、私はインストラクターについて行こうとした。`, words: [["at first", "最初は"], ["try to", "～しようとする"], ["follow", "ついて行く"], ["instructor", "インストラクター"]] },
  { id: 98, en: `His advice was different from yours.`, ja: `彼の忠告は、あなたのものとは違った。`, words: [["advice", "忠告"], ["different from", "～と違う"], ["yours", "あなたのもの"]] },
  { id: 99, en: `You must stay here until seven o'clock this evening.`, ja: `今晩の7時まで、ここにいなければいけません。`, words: [["must", "～しなければならない"], ["stay", "いる・滞在する"], ["until", "～まで"], ["evening", "夕方・晩"], ["seven", "7の"], ["o'clock", "～時"]] },
  { id: 100, en: `I am hungry because I didn't have breakfast this morning.`, ja: `今朝朝食を食べなかったので、私はおなかが減っている。`, words: [["hungry", "おなかが減った"], ["because", "なぜなら"], ["have breakfast", "朝食を食べる"], ["this morning", "今朝"]] },
  { id: 101, en: `I will help you with your Japanese after school.`, ja: `私は放課後に、あなたの日本語を手伝いましょう。`, words: [["help with", "～を手伝う"], ["you", "あなた"], ["Japanese", "日本語"], ["after school", "放課後"]] },
  { id: 102, en: `Many flags were raised over the field.`, ja: `競技場に多くの旗が掲げられた。`, words: [["many", "多くの"], ["flags", "旗"], ["raised", "掲げられた・上げた"], ["over", "～の上に"], ["field", "競技場・野原"]] },
  { id: 103, en: `I could hear the sound of the bell from far away.`, ja: `私は遠くから、ベルの音を聞くことができた。`, words: [["could", "～できた"], ["hear", "聞く"], ["sound", "音"], ["bell", "ベル"], ["from far away", "遠くから"]] },
  { id: 104, en: `Tom decided to buy the chair for her.`, ja: `トムは、彼女にそのいすを買うことを決めた。`, words: [["decide to", "～することに決める"], ["buy", "買う"], ["chair", "いす"], ["her", "彼女に・彼女の"]] },
  { id: 105, en: `The president was ready for his speech on social problems.`, ja: `大統領は、社会問題についてスピーチをする用意ができていた。`, words: [["president", "大統領"], ["be ready for", "～の用意ができた"], ["speech", "スピーチ・演説"], ["social", "社会の"], ["problems", "問題"], ["his", "彼の"]] },
  { id: 106, en: `I usually get up early in the morning to take a walk.`, ja: `私はいつも、散歩をするために朝早く起きます。`, words: [["usually", "いつも・たいてい"], ["get up", "起きる"], ["early", "早く"], ["take a walk", "散歩をする"], ["morning", "朝"]] },
  { id: 107, en: `We will play tennis at the schoolyard tomorrow.`, ja: `私たちは明日、校庭でテニスをするつもりだ。`, words: [["play", "（スポーツを）する"], ["tennis", "テニス"], ["schoolyard", "校庭"], ["tomorrow", "明日"], ["we", "私たち"], ["will", "～するつもり"]] },
  { id: 108, en: `Which color do you like more, black or brown?`, ja: `黒と茶、どちらの色がより好きですか？`, words: [["which", "どちらの"], ["color", "色"], ["more", "より～"], ["black", "黒"], ["brown", "茶"]] },
  { id: 109, en: `Are there any fresh fruit and vegetables in the store?`, ja: `お店には、新鮮な果物や野菜はありますか？`, words: [["any", "いくらかの"], ["fresh", "新鮮な"], ["fruit", "果物"], ["vegetables", "野菜"], ["store", "店"]] },
  { id: 110, en: `Mary is able to dance very well.`, ja: `メアリーは大変上手に踊ることができる。`, words: [["be able to", "～できる"], ["dance", "踊る"], ["very", "とても"], ["well", "上手に"]] },
  { id: 111, en: `I hope everything will turn out all right.`, ja: `すべてがうまくいくといいですね。`, words: [["hope", "望む"], ["everything", "すべて"], ["turn out", "～という結果になる"], ["all right", "うまくいって・大丈夫"]] },
  { id: 112, en: `Almost everyone believes that she will marry Bill.`, ja: `ほとんど全員の人が、彼女はビルと結婚すると信じている。`, words: [["almost", "ほとんど"], ["everyone", "すべての人"], ["believe", "信じる"], ["marry", "結婚する"]] },
  { id: 113, en: `She suddenly began to cry.`, ja: `彼女は突然に泣き始めた。`, words: [["she", "彼女"], ["suddenly", "突然"], ["begin to", "～し始める"], ["cry", "泣く"]] },
  { id: 114, en: `Remember to bring either a pen or a pencil.`, ja: `忘れずに、ペンか鉛筆のどちらかを持ってきなさい。`, words: [["remember to", "忘れずに～する"], ["bring", "持ってくる"], ["either...or", "～か～か"], ["pen", "ペン"], ["pencil", "鉛筆"]] },
  { id: 115, en: `The American newscaster is also known as a great artist.`, ja: `そのアメリカ人のニュースキャスターは、偉大な芸術家としても知られている。`, words: [["American", "アメリカの"], ["newscaster", "ニュースキャスター"], ["also", "～もまた"], ["be known as", "～として知られる"], ["great", "偉大な"], ["artist", "芸術家"]] },
  { id: 116, en: `There's not enough space for the piano beside the window.`, ja: `窓の脇には、ピアノを置く十分なスペースはない。`, words: [["enough", "十分な"], ["space", "スペース"], ["piano", "ピアノ"], ["beside", "～の脇に"], ["window", "窓"]] },
  { id: 117, en: `We will be able to take trips to the moon in the future.`, ja: `私たちは将来、月に旅をすることができるだろう。`, words: [["we", "私たち"], ["be able to", "～できる"], ["take a trip", "旅をする"], ["moon", "月"], ["in the future", "将来"]] },
  { id: 118, en: `I was lucky to get such a high math score.`, ja: `こんなに高い数学の得点をとって、私はラッキーだった。`, words: [["lucky", "幸運な"], ["such", "そんな・こんな"], ["high", "高い"], ["math", "数学"], ["score", "得点"]] },
  { id: 119, en: `How will you spend Christmas Day?`, ja: `クリスマスはどのように過ごしますか？`, words: [["how", "どのように"], ["spend", "過ごす"], ["Christmas", "クリスマス"]] },
  { id: 120, en: `How many kinds of life are there on land?`, ja: `地上には、どのくらいの種類の生物がいるのですか？`, words: [["how many", "いくつの"], ["kinds of", "～の種類"], ["life", "生物・生命"], ["land", "地上・陸"]] },
  { id: 121, en: `I hope that the 21st century is the age of peace.`, ja: `２１世紀は平和の時代であるとよいと思う。`, words: [["hope", "望む"], ["century", "世紀"], ["age", "時代"], ["peace", "平和"]] },
  { id: 122, en: `This necklace was in a box with a message from my father.`, ja: `このネックレスは、父からのメッセージといっしょに箱に入っていた。`, words: [["necklace", "ネックレス"], ["box", "箱"], ["message", "メッセージ"], ["from", "～から"], ["father", "父"]] },
  { id: 123, en: `Will you bring this big case into that gym?`, ja: `この大きなケースを、あの体育館に持ってきてくれますか？`, words: [["bring", "持ってくる"], ["big", "大きい"], ["case", "ケース・箱"], ["into", "～の中へ"], ["gym", "体育館"]] },
  { id: 124, en: `Perhaps, he may change his mind.`, ja: `たぶん、彼は気持ちを変えるかもしれない。`, words: [["perhaps", "たぶん"], ["may", "～かもしれない"], ["change one's mind", "気持ちを変える"], ["he", "彼"]] },
  { id: 125, en: `He gave up eating a lot for his health.`, ja: `彼は健康のために、たくさん食べることをやめた。`, words: [["give up", "やめる"], ["eat", "食べる"], ["a lot", "たくさん"], ["for", "～のために"], ["health", "健康"]] },
  { id: 126, en: `The comedian ran to the station to catch the train for Scotland.`, ja: `そのコメディアンは、スコットランド行きの列車に間に合うように駅へ走った。`, words: [["comedian", "コメディアン"], ["ran", "走った（runの過去形）"], ["station", "駅"], ["catch the train", "列車に間に合う"], ["Scotland", "スコットランド"]] },
  { id: 127, en: `During P.E. class, a terrible headache was killing me.`, ja: `体育の授業の間、猛烈な頭痛が私をひどく参らせた。`, words: [["during", "～の間"], ["class", "授業"], ["terrible", "猛烈な・ひどい"], ["headache", "頭痛"], ["kill", "ひどく参らせる・殺す"]] },
  { id: 128, en: `Mr. Kato broke the umbrella, so he threw it away.`, ja: `加藤さんは傘を壊したので、それを捨てました。`, words: [["broke", "壊した（breakの過去形）"], ["umbrella", "傘"], ["throw away", "捨てる"], ["so", "だから"]] },
  { id: 129, en: `Most of the houses in the country are built of wood.`, ja: `その国のほとんどの家が、木で建てられている。`, words: [["most of", "ほとんどの"], ["houses", "家"], ["country", "国"], ["be built of", "～で建てられる"], ["wood", "木"]] },
  { id: 130, en: `The doll's face looks like my dad.`, ja: `その人形の顔は、私のお父さんのようだ。`, words: [["doll", "人形"], ["face", "顔"], ["look like", "～のようだ"], ["dad", "お父さん"]] },
  { id: 131, en: `You must brush your teeth before going to sleep.`, ja: `寝る前に歯をみがかなければいけません。`, words: [["must", "～しなければならない"], ["brush", "みがく"], ["teeth", "歯（toothの複数形）"], ["before", "～の前に"], ["go to sleep", "寝る"]] },
  { id: 132, en: `You must not shout when you visit a shrine.`, ja: `神社を訪れたら、大きな声を出してはいけない。`, words: [["must not", "～してはいけない"], ["shout", "大声を出す"], ["when", "～のとき"], ["visit", "訪れる"], ["shrine", "神社"]] },
  { id: 133, en: `We have to set this statue on the grounds of the church.`, ja: `私たちは、教会の敷地にこの像を置かなければならない。`, words: [["have to", "～しなければならない"], ["set", "置く"], ["statue", "像"], ["grounds", "敷地"], ["church", "教会"]] },
  { id: 134, en: `I tried to shoot that gray bottle.`, ja: `私はあの灰色のビンを撃とうとした。`, words: [["try to", "～しようとする"], ["shoot", "撃つ"], ["gray", "灰色"], ["bottle", "ビン"]] },
  { id: 135, en: `Tom is a good man, though he sometimes forgets his promises.`, ja: `トムは良い男だが、ときどき約束を忘れる。`, words: [["good", "良い"], ["though", "～だが"], ["sometimes", "ときどき"], ["forget", "忘れる"], ["promises", "約束"]] },
  { id: 136, en: `Do you have enough time to gather some shells with me on the beach?`, ja: `私と海岸で貝殻を集める十分な時間はありますか？`, words: [["enough", "十分な"], ["gather", "集める"], ["shells", "貝殻"], ["with", "～と"], ["beach", "海岸"]] },
  { id: 137, en: `Several members of the group were invited to the concert.`, ja: `グループの数人が、そのコンサートに招待された。`, words: [["several", "数人の・いくつかの"], ["members", "メンバー"], ["group", "グループ"], ["invited", "招待された"], ["concert", "コンサート"]] },
  { id: 138, en: `I don't want to climb such a dangerous mountain alone.`, ja: `私は1人でそんな危険な山に登りたくない。`, words: [["climb", "登る"], ["such", "そんな"], ["dangerous", "危険な"], ["mountain", "山"], ["alone", "1人で"]] },
  { id: 139, en: `He was excited about the news from the police.`, ja: `彼は警察からの知らせに興奮した。`, words: [["be excited about", "～に興奮して"], ["news", "知らせ・ニュース"], ["police", "警察"], ["he", "彼"]] },
  { id: 140, en: `You should study geography to pass the exam.`, ja: `そのテストに合格するために、地理を勉強するべきだ。`, words: [["should", "～すべき"], ["study", "勉強する"], ["geography", "地理"], ["pass", "合格する"], ["exam", "試験"]] },
  { id: 141, en: `My first plane flight to Paris was an exciting event.`, ja: `私のパリへの初飛行は、ワクワクさせる出来事だった。`, words: [["first", "最初の"], ["plane", "飛行機"], ["flight", "飛行"], ["Paris", "パリ"], ["exciting", "ワクワクさせる"], ["event", "出来事"]] },
  { id: 142, en: `Young people should go abroad to understand the size of the world.`, ja: `若者は、世界の大きさを理解するために海外に行くべきである。`, words: [["young", "若い"], ["go abroad", "海外に行く"], ["understand", "理解する"], ["size", "大きさ"], ["world", "世界"]] },
  { id: 143, en: `We are looking forward to visiting the farm some day.`, ja: `私たちは、いつかその農場を訪れることを楽しみにしている。`, words: [["look forward to", "～を楽しみにする"], ["visit", "訪れる"], ["farm", "農場"], ["some day", "いつか"]] },
  { id: 144, en: `My wife got better, but I caught her bad cold.`, ja: `妻は回復したが、私に彼女のひどい風邪がうつった。`, words: [["wife", "妻"], ["get better", "回復する"], ["caught", "うつった・捕まえた"], ["bad", "ひどい・悪い"], ["cold", "風邪"]] },
  { id: 145, en: `I guess the cause of the fire in the drugstore will never be known.`, ja: `ドラッグストアの火事の原因は、決してわからないと推測します。`, words: [["guess", "推測する"], ["cause", "原因"], ["fire", "火事"], ["drugstore", "ドラッグストア"], ["never", "決して～ない"]] },
  { id: 146, en: `I ordered hot milk and apple pie.`, ja: `私は、温かいミルクとアップルパイを注文した。`, words: [["ordered", "注文した"], ["hot", "温かい・熱い"], ["milk", "ミルク"], ["apple pie", "アップルパイ"]] },
  { id: 147, en: `The newspaper says that a big earthquake happened in that area.`, ja: `新聞は、その地域で大きな地震が起きた、と伝えている。`, words: [["newspaper", "新聞"], ["earthquake", "地震"], ["happen", "起きる"], ["area", "地域"], ["big", "大きい"]] },
  { id: 148, en: `I'm glad my nurse in a hospital passed her driver's test.`, ja: `私は病院の看護師が、運転免許の試験に合格してうれしい。`, words: [["glad", "うれしい"], ["nurse", "看護師"], ["pass", "合格する"], ["driver's test", "運転免許試験"]] },
  { id: 149, en: `I am sorry I hurt you at school.`, ja: `学校であなたを傷つけてごめんなさい。`, words: [["sorry", "ごめんなさい・残念"], ["hurt", "傷つける"], ["you", "あなた"], ["school", "学校"]] },
  { id: 150, en: `There is a long line in front of the museum.`, ja: `博物館の前には、長い列がある。`, words: [["long", "長い"], ["line", "列"], ["in front of", "～の前に"], ["museum", "博物館"]] },
  { id: 151, en: `The party was over when I reached his home.`, ja: `私が彼の家に着いたとき、そのパーティは終わった。`, words: [["party", "パーティ"], ["over", "終わって"], ["when", "～のとき"], ["reached", "着いた"], ["home", "家"]] },
  { id: 152, en: `Many visitors were interested in the shape of the house.`, ja: `多くの訪問客は、その家の形に興味があった。`, words: [["many", "多くの"], ["visitors", "訪問客"], ["be interested in", "～に興味がある"], ["shape", "形"], ["house", "家"]] },
  { id: 153, en: `In my opinion, this practice was fine.`, ja: `私の意見では、この練習はまずまずだった。`, words: [["in my opinion", "私の意見では"], ["practice", "練習"], ["fine", "まずまず・良い"]] },
  { id: 154, en: `Thank you for cleaning up the kitchen.`, ja: `キッチンを掃除してくれてありがとう。`, words: [["thank you for", "～をありがとう"], ["clean up", "掃除する"], ["kitchen", "キッチン"], ["you", "あなた"]] },
  { id: 155, en: `She realized that some students told lies.`, ja: `彼女は、数人の生徒がうそをついていると気づいていた。`, words: [["realized", "気づいた"], ["students", "生徒"], ["tell a lie", "うそをつく"], ["some", "数人の・いくらかの"]] },
  { id: 156, en: `Is there anything sweet to serve the guest?`, ja: `お客さんに出す、何か甘いものはありますか？`, words: [["anything", "何か"], ["sweet", "甘い"], ["serve", "出す・給仕する"], ["guest", "客"]] },
  { id: 157, en: `Just a moment, I will be right back.`, ja: `ちょっと待ってください、すぐに戻ります。`, words: [["just a moment", "ちょっと待って"], ["moment", "瞬間"], ["right back", "すぐに戻る"]] },
  { id: 158, en: `If he comes back soon, shall we go shopping?`, ja: `もし彼がすぐに帰ってくれば、買い物に行きませんか？`, words: [["come back", "帰ってくる"], ["soon", "すぐに"], ["shall we", "～しませんか"], ["go shopping", "買い物に行く"], ["if", "もし"]] },
  { id: 159, en: `The interpreter encouraged me to do a homestay in Hawaii.`, ja: `その通訳は、私にハワイでのホームステイをするように促した。`, words: [["interpreter", "通訳"], ["encourage", "促す・励ます"], ["homestay", "ホームステイ"], ["Hawaii", "ハワイ"]] },
  { id: 160, en: `We could feel the nation's tradition in their daily activities.`, ja: `私たちは人々の日常活動の中に、その国の伝統を感じることができた。`, words: [["feel", "感じる"], ["nation", "国"], ["tradition", "伝統"], ["daily", "日常の"], ["activities", "活動"]] },
  { id: 161, en: `The best way to master English is to read a textbook aloud again and again.`, ja: `英語を習得する最も良い方法は、何度も教科書を音読することだ。`, words: [["best way", "最も良い方法"], ["master", "習得する"], ["read", "読む"], ["textbook", "教科書"], ["aloud", "声を出して"], ["again and again", "何度も"]] },
  { id: 162, en: `He appears to be surprised at the strict laws of this town.`, ja: `彼は、この町の厳しい規則に驚いているように見える。`, words: [["appear to", "～のように見える"], ["be surprised at", "～に驚く"], ["strict", "厳しい"], ["laws", "規則・法律"], ["town", "町"]] },
  { id: 163, en: `In the movie, the enemy was arrested for making atomic bombs in Russia.`, ja: `その映画の中で敵は、ロシアで核爆弾を作り逮捕された。`, words: [["movie", "映画"], ["enemy", "敵"], ["arrested", "逮捕された"], ["atomic bomb", "原子爆弾"], ["Russia", "ロシア"]] },
  { id: 164, en: `How long will you stay in this village?`, ja: `この村にどのくらい滞在しますか？`, words: [["how long", "どのくらい（の期間）"], ["stay", "滞在する"], ["village", "村"]] },
  { id: 165, en: `Most of the students in Japan study English in high school.`, ja: `日本のほとんどの学生は、高校で英語を勉強する。`, words: [["most of", "ほとんどの"], ["students", "学生"], ["high school", "高校"]] },
  { id: 166, en: `What happened? You seem a bit sad.`, ja: `どうしたの？ 少し悲しそうに見えるよ。`, words: [["happen", "起きる"], ["seem", "～のように見える"], ["a bit", "少し"], ["sad", "悲しい"]] },
  { id: 167, en: `My grandmother sent this nice present to me.`, ja: `祖母は私に、このすてきなプレゼントを送ってくれた。`, words: [["grandmother", "祖母"], ["sent", "送った（sendの過去形）"], ["nice", "すてきな"], ["present", "プレゼント"]] },
  { id: 168, en: `Electricity and gas are not free, so don't waste them.`, ja: `電気とガスはただではないから、むだ使いするな。`, words: [["electricity", "電気"], ["gas", "ガス"], ["free", "ただの・自由な"], ["waste", "むだ使いする"]] },
  { id: 169, en: `Which do you like better, cheese or sausage?`, ja: `チーズとソーセージ、どちらがより好きですか？`, words: [["better", "より好き・より良い"], ["cheese", "チーズ"], ["sausage", "ソーセージ"]] },
  { id: 170, en: `Don't worry. I'll return to the office with an airline ticket by eight o'clock.`, ja: `心配しないで。8時までには、航空券を持って会社に戻ります。`, words: [["worry", "心配する"], ["return", "戻る"], ["office", "会社・事務所"], ["airline ticket", "航空券"], ["by", "～までに"], ["eight", "8の"], ["o'clock", "～時"]] },
  { id: 171, en: `Here is a pocket map of the zoo.`, ja: `これが、その動物園のポケット地図です。`, words: [["here is", "これが～です"], ["pocket", "ポケット"], ["map", "地図"], ["zoo", "動物園"]] },
  { id: 172, en: `An international music festival was held at the foot of Mt. Fuji.`, ja: `国際音楽祭が、富士山のふもとで開かれた。`, words: [["international", "国際的な"], ["festival", "祭り"], ["held", "開かれた"], ["foot", "ふもと・足"]] },
  { id: 173, en: `I would like to know your favorite poem.`, ja: `私はあなたのお気に入りの詩が知りたい。`, words: [["would like to", "～したい"], ["favorite", "お気に入りの"], ["poem", "詩"], ["I", "私"], ["your", "あなたの"]] },
  { id: 174, en: `In the end, he gave me medicine.`, ja: `ついに、彼は私に薬を出してくれた。`, words: [["in the end", "ついに・結局"], ["gave", "与えた（giveの過去形）"], ["medicine", "薬"], ["he", "彼"], ["me", "私に"]] },
  { id: 175, en: `We are responsible for keeping Mt. Fuji clean.`, ja: `私たちには、富士山をきれいにしておく責任がある。`, words: [["be responsible for", "～に責任がある"], ["keep", "～しておく・保つ"], ["clean", "きれいな"]] },
  { id: 176, en: `Today's waves are low, so we can swim in safety.`, ja: `今日の波は低い、だから安全に泳ぐことができる。`, words: [["waves", "波"], ["low", "低い"], ["swim", "泳ぐ"], ["in safety", "安全に"]] },
  { id: 177, en: `I am fond of the flavor of chocolate ice cream.`, ja: `私はチョコレートアイスクリームの風味が好きだ。`, words: [["be fond of", "～が好き"], ["flavor", "風味"], ["chocolate", "チョコレート"], ["ice cream", "アイスクリーム"]] },
  { id: 178, en: `We should know more about the value of freedom of choice.`, ja: `私たちは、選択の自由の重要性をもっと知るべきだ。`, words: [["value", "価値・重要性"], ["freedom", "自由"], ["choice", "選択"], ["we", "私たち"], ["more", "もっと"]] },
  { id: 179, en: `Every employee has to show their identity card to enter this building.`, ja: `すべての従業員は、この建物に入るために、身分証明書を見せなければならない。`, words: [["every", "すべての"], ["employee", "従業員"], ["show", "見せる"], ["identity", "身分"], ["enter", "入る"], ["building", "建物"]] },
  { id: 180, en: `There are quite a few animals on the earth.`, ja: `地球上には、かなり多くの動物がいる。`, words: [["quite a few", "かなり多くの"], ["animals", "動物"], ["earth", "地球"]] },
  { id: 181, en: `Prices will not drop for a while.`, ja: `当分の間、物価は下がらないだろう。`, words: [["prices", "物価"], ["drop", "下がる・落とす"], ["for a while", "当分の間"]] },
  { id: 182, en: `When I was painting the wall white, my neighbor was beating the drums loudly.`, ja: `私が壁を白く塗っていたとき、隣人は太鼓を騒々しくたたいていた。`, words: [["paint", "塗る"], ["wall", "壁"], ["white", "白い"], ["neighbor", "隣人"], ["beat", "たたく"], ["drums", "太鼓"], ["loudly", "騒々しく"]] },
  { id: 183, en: `My dream is to become a scientist.`, ja: `私の夢は科学者になることだ。`, words: [["dream", "夢"], ["become", "～になる"], ["scientist", "科学者"]] },
  { id: 184, en: `You have plenty of time to make a final decision.`, ja: `あなたには、最終決断をするためのたくさんの時間があります。`, words: [["plenty of", "たくさんの"], ["make a decision", "決断をする"], ["final", "最終の"], ["decision", "決断"]] },
  { id: 185, en: `My uncle went into the store to buy some toys for his baby.`, ja: `私のおじは彼の赤ん坊におもちゃを買うためにそのお店に入った。`, words: [["uncle", "おじ"], ["go into", "～に入る"], ["toys", "おもちゃ"], ["baby", "赤ん坊"]] },
  { id: 186, en: `The history teacher said, "The period of World War II was very dark."`, ja: `歴史の先生は、「第二次世界大戦の期間はとても暗かった」と言った。`, words: [["history", "歴史"], ["period", "期間"], ["World War", "世界大戦"], ["dark", "暗い"]] },
  { id: 187, en: `We are willing to support you in your effort to stop global warming.`, ja: `私たちは喜んで、あなたの地球温暖化を止める努力を支持する。`, words: [["be willing to", "喜んで～する"], ["support", "支持する"], ["effort", "努力"], ["stop", "止める"], ["global warming", "地球温暖化"]] },
  { id: 188, en: `In fact, both Bill and Jenny attended the lesson.`, ja: `実際は、ビルとジェニーの両方が授業に出席しました。`, words: [["in fact", "実際は"], ["both...and", "～も～も両方"], ["attended", "出席した"], ["lesson", "授業"]] },
  { id: 189, en: `She bought foreign furniture for me from a department store in this country.`, ja: `彼女はこのデパートで、私に外国の家具を買ってくれた。`, words: [["foreign", "外国の"], ["furniture", "家具"], ["department store", "デパート"], ["country", "国"]] },
  { id: 190, en: `At the end of class, we will take a short rest.`, ja: `授業の終わりには、私たちは短い休憩を取るだろう。`, words: [["at the end of", "～の終わりに"], ["take a rest", "休憩する"], ["short", "短い"], ["rest", "休憩"]] },
  { id: 191, en: `Many photographers left for that state to take pictures.`, ja: `多くの写真家が、写真をとるためにあの州に出発した。`, words: [["photographers", "写真家"], ["leave for", "～に出発する"], ["state", "州"], ["take pictures", "写真をとる"]] },
  { id: 192, en: `The heat of the sun is an important resource for human beings.`, ja: `太陽の熱は、人類にとって重要な資源である。`, words: [["heat", "熱"], ["sun", "太陽"], ["important", "重要な"], ["resource", "資源"], ["human beings", "人類"]] },
  { id: 193, en: `The singer on the stage stopped smiling.`, ja: `そのステージ上の歌手は、ほほえむことをやめた。`, words: [["singer", "歌手"], ["stage", "ステージ"], ["stop", "やめる・止まる"], ["smile", "ほほえむ"]] },
  { id: 194, en: `My hobby is watching professional volleyball on TV.`, ja: `私の趣味は、テレビでプロのバレーボールを見ることです。`, words: [["hobby", "趣味"], ["watch", "見る"], ["professional", "プロの"], ["volleyball", "バレーボール"]] },
  { id: 195, en: `I needed a telephone to communicate with my mother, but I didn't have one.`, ja: `私の母と連絡をとるために電話が必要だったが、持っていなかった。`, words: [["need", "必要とする"], ["telephone", "電話"], ["communicate with", "～と連絡をとる"], ["mother", "母"]] },
  { id: 196, en: `Finally, he developed a new cell phone.`, ja: `ついに、彼は新しい携帯電話を開発した。`, words: [["finally", "ついに"], ["develop", "開発する"], ["cell phone", "携帯電話"], ["he", "彼"], ["new", "新しい"]] },
  { id: 197, en: `There are hundreds of ancient heritages in Italy.`, ja: `イタリアには何百もの古代遺産がある。`, words: [["hundreds of", "何百もの"], ["ancient", "古代の"], ["heritage", "遺産"], ["Italy", "イタリア"]] },
  { id: 198, en: `The worker filled the bucket with the cool water.`, ja: `その労働者は、バケツを冷たい水でいっぱいにした。`, words: [["worker", "労働者"], ["fill", "いっぱいにする"], ["bucket", "バケツ"], ["cool", "冷たい・涼しい"], ["water", "水"]] },
  { id: 199, en: `I am proud that my children are not only smart but also friendly toward everybody.`, ja: `私は自分の子どもたちが利口なだけでなく、誰に対してでも友好的なことに誇りを持っている。`, words: [["be proud that", "～を誇りに思う"], ["children", "子ども"], ["not only...but also", "～だけでなく～も"], ["smart", "利口な"], ["friendly", "友好的な"], ["toward", "～に対して"]] },
  { id: 200, en: `I shook hands with the old man in the wheelchair.`, ja: `私は、車いすに乗った年をとった男性と握手をした。`, words: [["shake hands", "握手する"], ["old", "年をとった・古い"], ["man", "男・男性"], ["wheelchair", "車いす"]] },
  { id: 201, en: `Because he was as honest as Lincoln, he refused to play a trick.`, ja: `彼はリンカーンと同じくらい正直だったので、策略を用いることを拒否した。`, words: [["as...as", "～と同じくらい"], ["honest", "正直な"], ["refuse to", "～を拒否する"], ["play a trick", "策略を用いる"], ["Lincoln", "リンカーン"]] },
  { id: 202, en: `This Halloween costume is cheaper than ours.`, ja: `このハロウィーンの衣装は、私たちのよりも安い。`, words: [["Halloween", "ハロウィーン"], ["costume", "衣装"], ["cheaper", "より安い"], ["ours", "私たちのもの"], ["this", "この・これ"]] },
  { id: 203, en: `The most amazing thing of the festival was the colorful fireworks.`, ja: `そのお祭りでいちばん驚いたことは、色鮮やかな花火だった。`, words: [["most", "最も"], ["amazing", "驚くべき"], ["festival", "祭り"], ["colorful", "色鮮やかな"], ["fireworks", "花火"]] },
  { id: 204, en: `What is your purpose for coming here?`, ja: `ここに来たあなたの目的はなんですか？`, words: [["purpose", "目的"], ["here", "ここ"], ["coming", "来ること"]] },
  { id: 205, en: `My pet died of cancer this afternoon.`, ja: `私のペットは今日の午後、がんのために死んだ。`, words: [["pet", "ペット"], ["die of", "～で死ぬ"], ["cancer", "がん"], ["this afternoon", "今日の午後"], ["my", "私の"]] },
  { id: 206, en: `In those days, this castle was the center of the city.`, ja: `当時は、この城は市の中心であった。`, words: [["in those days", "当時は"], ["castle", "城"], ["center", "中心"], ["city", "市・都市"], ["this", "この・これ"]] },
  { id: 207, en: `Long ago, the hill was covered with green grass.`, ja: `昔、その丘は緑の芝におおわれていた。`, words: [["long ago", "昔"], ["hill", "丘"], ["be covered with", "～におおわれる"], ["green", "緑の"], ["grass", "芝・草"]] },
  { id: 208, en: `The gentleman recorded his volunteer work with his video camera.`, ja: `その紳士は自分のビデオカメラで、彼のボランティア活動を記録した。`, words: [["gentleman", "紳士"], ["recorded", "記録した"], ["volunteer", "ボランティア"], ["video camera", "ビデオカメラ"], ["his", "彼の"]] },
  { id: 209, en: `My grandpa selected this jacket for her gift.`, ja: `私のおじいちゃんは、このジャケットを彼女への贈り物に選んだ。`, words: [["grandpa", "おじいちゃん"], ["selected", "選んだ"], ["jacket", "ジャケット"], ["gift", "贈り物"], ["her", "彼女の・彼女に"]] },
  { id: 210, en: `You have to get tough training to win the race against the runner from Kenya.`, ja: `あなたがそのケニアから来たランナーとのレースに勝つためには、苦しいトレーニングをしなければならない。`, words: [["tough", "苦しい・タフな"], ["training", "トレーニング"], ["win", "勝つ"], ["race", "レース"], ["against", "～に対して"], ["runner", "ランナー"], ["Kenya", "ケニア"]] },
  { id: 211, en: `Many leaves were blown by the strong wind from the east.`, ja: `東からの強い風によって、たくさんの葉が吹き飛ばされた。`, words: [["leaves", "葉（leafの複数形）"], ["blown", "吹き飛ばされた"], ["strong", "強い"], ["wind", "風"], ["east", "東"]] },
  { id: 212, en: `My grandparents were impressed by the delicious spaghetti.`, ja: `私の祖父母は、そのおいしいスパゲッティに感動した。`, words: [["grandparents", "祖父母"], ["be impressed by", "～に感動する"], ["delicious", "おいしい"], ["spaghetti", "スパゲッティ"], ["my", "私の"]] },
  { id: 213, en: `My cousin was born in North America.`, ja: `私のいとこは、北アメリカで生まれた。`, words: [["cousin", "いとこ"], ["be born", "生まれる"], ["North America", "北アメリカ"], ["my", "私の"]] },
  { id: 214, en: `There are many cows and chickens in this part of England.`, ja: `イングランドのこの地方には、たくさんの牛と鶏がいる。`, words: [["many", "多くの"], ["cows", "牛"], ["chickens", "鶏"], ["part", "地方・部分"], ["England", "イングランド"]] },
  { id: 215, en: `I introduced my partner to my classmate last night.`, ja: `私は昨晩、恋人を自分のクラスメートに紹介した。`, words: [["introduce", "紹介する"], ["partner", "恋人・相棒"], ["classmate", "クラスメート"], ["last night", "昨晩"], ["my", "私の"]] },
  { id: 216, en: `The ALT has a wide knowledge of nature.`, ja: `そのALTは、自然について幅広い知識を持っている。`, words: [["wide", "幅広い"], ["knowledge", "知識"], ["nature", "自然"], ["ALT", "外国語指導助手"]] },
  { id: 217, en: `The body of the tower is made of stone.`, ja: `その塔の中心部は、石でできている。`, words: [["body", "中心部・体"], ["tower", "塔"], ["be made of", "～でできている"], ["stone", "石"]] },
  { id: 218, en: `In the last of the tragedy, the poor prince is treated like trash.`, ja: `その悲劇の最後で、かわいそうな王子はゴミのように扱われた。`, words: [["tragedy", "悲劇"], ["poor", "かわいそうな・貧しい"], ["prince", "王子"], ["treat", "扱う"], ["trash", "ごみ"], ["like", "～のように"]] },
  { id: 219, en: `Will you write the meaning of the gesture on the blackboard?`, ja: `黒板にそのジェスチャーの意味を書いてくれますか？`, words: [["write", "書く"], ["meaning", "意味"], ["gesture", "ジェスチャー"], ["blackboard", "黒板"], ["you", "あなた"]] },
  { id: 220, en: `However, her eyes were filled with tears.`, ja: `しかしながら、彼女の目は涙でいっぱいだった。`, words: [["however", "しかしながら"], ["eyes", "目"], ["be filled with", "～でいっぱい"], ["tears", "涙"], ["her", "彼女の"]] },
  { id: 221, en: `The nuclear engineer earned a fortune in Seoul.`, ja: `その原子力技術者は、ソウルで財産を手に入れた。`, words: [["nuclear", "原子力の"], ["engineer", "技術者"], ["earned", "手に入れた・稼いだ"], ["fortune", "財産"], ["Seoul", "ソウル"]] },
  { id: 222, en: `Burning fossil fuel creates CO2.`, ja: `化石燃料の燃焼は、CO2を作り出す。`, words: [["burning", "燃焼・燃やすこと"], ["fossil fuel", "化石燃料"], ["create", "作り出す"], ["CO2", "二酸化炭素"]] },
  { id: 223, en: `The detective smoked a lot in public.`, ja: `その探偵は、人前でたくさんタバコを吸った。`, words: [["detective", "探偵"], ["smoke", "タバコを吸う"], ["in public", "人前で"], ["a lot", "たくさん"]] },
  { id: 224, en: `The actor lit a candle in the silent theater.`, ja: `その俳優は静かな劇場の中で、ろうそくに火をつけた。`, words: [["actor", "俳優"], ["lit", "火をつけた（lightの過去形）"], ["candle", "ろうそく"], ["silent", "静かな"], ["theater", "劇場"]] },
  { id: 225, en: `He has collected CDs since he was a child.`, ja: `彼は子どものときから、CDを集めている。`, words: [["collect", "集める"], ["since", "～以来"], ["child", "子ども"], ["CD", "CD"], ["he", "彼"]] },
  { id: 226, en: `Have you ever buried some trash there?`, ja: `今までに、そこにゴミを埋めたことはありますか？`, words: [["ever", "今までに"], ["buried", "埋めた"], ["trash", "ごみ"], ["there", "そこに"]] },
  { id: 227, en: `The chef hasn't prepared the beef sandwiches yet.`, ja: `シェフはまだ、ビーフサンドイッチを準備していない。`, words: [["chef", "シェフ"], ["prepared", "準備した"], ["beef", "牛肉"], ["sandwich", "サンドイッチ"], ["yet", "まだ"]] },
  { id: 228, en: `I will finish my homework as soon as I can.`, ja: `できるだけ早く、宿題を終わらせます。`, words: [["finish", "終わらせる"], ["homework", "宿題"], ["as soon as one can", "できるだけ早く"], ["I", "私"]] },
  { id: 229, en: `He can remember the name of everyone that he meets.`, ja: `彼は、会うすべての人の名前を覚えることができる`, words: [["remember", "覚える"], ["name", "名前"], ["everyone", "すべての人"], ["meet", "会う"]] },
  { id: 230, en: `On a day like this, it is dangerous to swim in the sea.`, ja: `このような日に、海で泳ぐことは危険だ。`, words: [["like this", "このような"], ["dangerous", "危険な"], ["swim", "泳ぐ"], ["sea", "海"]] },
  { id: 231, en: `It isn't easy to pick a good family doctor.`, ja: `よいかかりつけの医師を選ぶことは、簡単ではない。`, words: [["easy", "簡単な"], ["pick", "選ぶ"], ["family doctor", "かかりつけの医師"], ["good", "よい"]] },
  { id: 232, en: `No person answered the last question on the quiz.`, ja: `だれも、テストの最後の問題に答えなかった。`, words: [["no", "～ない"], ["person", "人"], ["answered", "答えた"], ["question", "問題・質問"], ["quiz", "テスト・クイズ"]] },
  { id: 233, en: `I have already received a letter from my dear friend.`, ja: `私はすでに、仲のよい友だちから手紙を受けとった。`, words: [["already", "すでに"], ["received", "受けとった"], ["letter", "手紙"], ["dear", "親愛なる"], ["friend", "友だち"]] },
  { id: 234, en: `He has just closed the window of the classroom.`, ja: `彼はちょうど、その教室の窓を閉めたところだ。`, words: [["just", "ちょうど"], ["closed", "閉めた"], ["window", "窓"], ["classroom", "教室"]] },
  { id: 235, en: `It was useful to study with friends for the test.`, ja: `テストのために友だちと勉強するのは役に立った。`, words: [["useful", "役に立つ"], ["study", "勉強する"], ["test", "テスト"]] },
  { id: 236, en: `It is difficult to explain this card game.`, ja: `このカードゲームを説明することは難しい`, words: [["difficult", "難しい"], ["explain", "説明する"], ["card game", "カードゲーム"], ["this", "この・これ"], ["it", "それ"]] },
  { id: 237, en: `Go straight for six hundred meters, then you will find the college on your right.`, ja: `600メートルまっすぐ行きなさい、すると右側に大学が見えるでしょう。`, words: [["go straight", "まっすぐ行く"], ["meters", "メートル"], ["then", "すると・それから"], ["find", "見つける"], ["college", "大学"], ["right", "右"], ["six hundred", "600"]] },
  { id: 238, en: `The old guide taught us how to walk in the forest.`, ja: `年配のガイドは、私たちに森の歩き方を教えてくれた。`, words: [["old", "年配の"], ["guide", "ガイド"], ["taught", "教えた（teachの過去形）"], ["how to", "～の仕方"], ["forest", "森"]] },
  { id: 239, en: `It is common for me to wash my car once a month.`, ja: `月に1度車を洗うのは、私にとってふつうのことだ。`, words: [["common", "ふつうの・一般的な"], ["wash", "洗う"], ["once a month", "月に1度"], ["car", "車"]] },
  { id: 240, en: `It's hard to keep the traditional customs forever.`, ja: `永遠に伝統的習慣を維持することは、たいへんである。`, words: [["hard", "たいへんな・難しい"], ["keep", "維持する"], ["traditional", "伝統的な"], ["customs", "習慣"], ["forever", "永遠に"]] },
  { id: 241, en: `We have traveled around the world for a long time.`, ja: `私たちは長い間、世界中を旅している。`, words: [["travel", "旅する"], ["around the world", "世界中"], ["for a long time", "長い間"], ["we", "私たち"]] },
  { id: 242, en: `I have never drunk coffee without sugar.`, ja: `砂糖を入れずにコーヒーを飲んだことは、一度もない。`, words: [["never", "一度もない"], ["drink", "飲む"], ["coffee", "コーヒー"], ["without", "～なしで"], ["sugar", "砂糖"]] },
  { id: 243, en: `Please tell me what subject you like the best.`, ja: `あなたがいちばん好きな教科を、私に教えて下さい。`, words: [["tell", "教える・伝える"], ["subject", "教科"], ["the best", "いちばん"], ["me", "私に"]] },
  { id: 244, en: `The boy carrying a magazine under his arm is Tom's son.`, ja: `腕に雑誌を抱えて運んでいる男の子は、トムの息子です。`, words: [["boy", "男の子"], ["carry", "運ぶ"], ["magazine", "雑誌"], ["arm", "腕"], ["son", "息子"]] },
  { id: 245, en: `Our baseball coach works for a company that makes baseball gloves.`, ja: `私たちの野球コーチは、野球のグラブを作る会社で働いている。`, words: [["baseball", "野球"], ["coach", "コーチ"], ["work for", "～で働く"], ["company", "会社"], ["gloves", "グラブ・手袋"]] },
  { id: 246, en: `It's a pleasure to have a chance to interview that musician.`, ja: `あの音楽家にインタビューをする機会を持つとは、光栄である。`, words: [["pleasure", "光栄・喜び"], ["chance", "機会"], ["interview", "インタビューする"], ["musician", "音楽家"]] },
  { id: 247, en: `He is very busy writing a book.`, ja: `彼は本を書くのにとても忙しい。`, words: [["busy", "忙しい"], ["write", "書く"], ["book", "本"], ["he", "彼"], ["very", "とても"]] },
  { id: 248, en: `The fourth floor was full of people looking for jobs.`, ja: `4階は、仕事を探している人でいっぱいだった。`, words: [["fourth", "4番目の"], ["floor", "階"], ["be full of", "～でいっぱい"], ["look for", "～を探す"], ["jobs", "仕事"]] },
  { id: 249, en: `Do you know how to exchange greetings in Spanish?`, ja: `スペイン語でのあいさつの交わし方を知っていますか？`, words: [["how to", "～の仕方"], ["exchange", "交わす・交換する"], ["greetings", "あいさつ"], ["Spanish", "スペイン語"]] },
  { id: 250, en: `Though the ship disappeared from sight, they kept singing a song in a loud voice.`, ja: `その船は視界から消えたが、彼らは大きな声で歌い続けた。`, words: [["though", "～だが"], ["ship", "船"], ["disappeared", "消えた"], ["sight", "視界"], ["keep ~ing", "～し続ける"], ["song", "歌"], ["in a loud voice", "大きな声で"]] },
  { id: 251, en: `She learned how to bake bread from her friend.`, ja: `彼女は、パンの焼き方を友だちから習った。`, words: [["learn", "習う・学ぶ"], ["how to", "～の仕方"], ["bake", "焼く"], ["bread", "パン"]] },
  { id: 252, en: `It is impossible to steal these cherry blossoms.`, ja: `これらの桜の花を盗むことは不可能だ。`, words: [["impossible", "不可能な"], ["steal", "盗む"], ["cherry blossoms", "桜の花"], ["these", "これらの"], ["it", "それ"]] },
  { id: 253, en: `I have been to the UK twice.`, ja: `私は英国【イギリス】に2回行ったことがある。`, words: [["have been to", "～に行ったことがある"], ["UK", "英国・イギリス"], ["twice", "2回"]] },
  { id: 254, en: `The minister asked him to continue to trade natural gas.`, ja: `大臣は、天然ガスの貿易を続けるように彼を頼んだ。`, words: [["minister", "大臣"], ["ask", "頼む"], ["continue", "続ける"], ["trade", "貿易・取引する"], ["natural gas", "天然ガス"]] },
  { id: 255, en: `Neither war nor guns make us happy.`, ja: `戦争も銃も、私たちを幸せにしない。`, words: [["neither...nor", "～も～もない"], ["war", "戦争"], ["guns", "銃"], ["happy", "幸せな"]] },
  { id: 256, en: `It is often said that dolphins are nervous.`, ja: `イルカは神経質だと、しばしば言われる。`, words: [["often", "しばしば"], ["it is said that", "～と言われる"], ["dolphins", "イルカ"], ["nervous", "神経質な"]] },
  { id: 257, en: `Please move the heavy machine downstairs as soon as possible.`, ja: `できるだけ早く、その重たい機械を階下に動かしてください。`, words: [["move", "動かす"], ["heavy", "重たい"], ["machine", "機械"], ["downstairs", "階下に"], ["as soon as possible", "できるだけ早く"]] },
  { id: 258, en: `In my view, it is necessary for everybody to keep a diary.`, ja: `私の考えでは、誰もが日記をつけることが必要だ。`, words: [["in my view", "私の考えでは"], ["necessary", "必要な"], ["everybody", "誰もが"], ["keep a diary", "日記をつける"]] },
  { id: 259, en: `Why don't you give Tom another chance?`, ja: `トムにもう一度チャンスを与えませんか？`, words: [["why don't you", "～しませんか"], ["give", "与える"], ["another", "もう一つの"], ["chance", "チャンス・機会"]] },
  { id: 260, en: `It takes about half an hour to get to the university by taxi.`, ja: `タクシーで大学に到着するまで、半時間ほどかかる。`, words: [["it takes", "（時間が）かかる"], ["half an hour", "半時間"], ["get to", "～に着く"], ["university", "大学"], ["taxi", "タクシー"]] },
  { id: 261, en: `This mystery is quite simple to solve.`, ja: `この謎は、解くのがかなり簡単だ。`, words: [["mystery", "謎"], ["quite", "かなり"], ["simple", "簡単な"], ["solve", "解く"]] },
  { id: 262, en: `You had better hurry to school, because you were late for class yesterday.`, ja: `学校に急いだほうがいいよ、昨日、授業に遅刻したのだから。`, words: [["had better", "～したほうがいい"], ["hurry", "急ぐ"], ["be late for", "～に遅刻する"], ["class", "授業"]] },
  { id: 263, en: `The Japanese government has studied the economic system in China.`, ja: `日本政府は中国の経済制度を研究している。`, words: [["government", "政府"], ["study", "研究する"], ["economic", "経済の"], ["system", "制度"], ["China", "中国"]] },
  { id: 264, en: `It's great fun to perform chemical experiments in class.`, ja: `授業中に化学実験を行うことは、大きな楽しみである。`, words: [["great fun", "大きな楽しみ"], ["perform", "行う"], ["chemical", "化学の"], ["experiments", "実験"]] },
  { id: 265, en: `One of my teammates eats hamburgers and pizza for dinner every day.`, ja: `私のチームメイトの1人は、毎日夕食としてハンバーガーとピザを食べる。`, words: [["one of", "～の一つ"], ["teammates", "チームメイト"], ["hamburger", "ハンバーガー"], ["pizza", "ピザ"], ["dinner", "夕食"], ["every day", "毎日"]] },
  { id: 266, en: `He is good at making speeches on the role of women.`, ja: `彼は、女性の役割について演説をするのが得意だ。`, words: [["be good at", "～が得意"], ["make a speech", "演説をする"], ["role", "役割"], ["women", "女性（womanの複数形）"]] },
  { id: 267, en: `The airport is crowded with people who want to see the actress.`, ja: `空港は、その女優を見たい人で混んでいる。`, words: [["airport", "空港"], ["be crowded with", "～で混んでいる"], ["actress", "女優"]] },
  { id: 268, en: `He pointed his finger at the passenger whose sweater was similar to mine.`, ja: `彼は、私のと似たセーターを着た乗客を指さした。`, words: [["point at", "～を指さす"], ["finger", "指"], ["passenger", "乗客"], ["sweater", "セーター"], ["similar to", "～に似た"]] },
  { id: 269, en: `Where did he lose the soccer ball that his father gave him as a birthday present?`, ja: `どこで彼は、誕生日プレゼントとして父親が与えたサッカーボールをなくしたのですか？`, words: [["lose", "なくす"], ["soccer ball", "サッカーボール"], ["birthday present", "誕生日プレゼント"], ["where", "どこで"], ["his", "彼の"]] },
  { id: 270, en: `It is surprising that the princess was a film star.`, ja: `その王女が映画スターだったとは驚きだ。`, words: [["surprising", "驚き・驚くべき"], ["princess", "王女"], ["film star", "映画スター"], ["it", "それ"], ["that", "あの・その"]] },
  { id: 271, en: `I can't imagine that anybody will accept the plan.`, ja: `だれも、その計画を受け入れるとは思えない。`, words: [["imagine", "想像する"], ["anybody", "だれも・誰か"], ["accept", "受け入れる"], ["plan", "計画"]] },
  { id: 272, en: `They compared the cost of living between both prefectures.`, ja: `彼らは両県の生活費を比較した。`, words: [["compared", "比較した"], ["cost of living", "生活費"], ["both", "両方の"], ["prefectures", "県"]] },
  { id: 273, en: `Fine arts cured a huge hole in my heart.`, ja: `美術が私の心の巨大な穴を癒やしてくれた。`, words: [["fine arts", "美術"], ["cured", "癒やした・治した"], ["huge", "巨大な"], ["hole", "穴"], ["heart", "心"]] },
  { id: 274, en: `Dr. Williams was injured in the traffic accident.`, ja: `ウイリアムズ博士は交通事故でけがをした。`, words: [["injured", "けがをした"], ["traffic accident", "交通事故"], ["Dr.", "博士・医師"]] },
  { id: 275, en: `His musical talent is below the level of his sister's.`, ja: `彼の音楽の才能は、妹［姉］の水準を下回る。`, words: [["musical", "音楽の"], ["talent", "才能"], ["below", "～を下回る・の下に"], ["level", "水準"]] },
  { id: 276, en: `The farmer provides his horse with carrots every morning.`, ja: `その農夫は毎朝、自分の馬にニンジンを与える。`, words: [["farmer", "農夫"], ["provide A with B", "AにBを供給する"], ["horse", "馬"], ["carrots", "ニンジン"], ["every morning", "毎朝"]] },
  { id: 277, en: `Mary is afraid of barking dogs.`, ja: `メアリーは吠えている犬を怖がる。`, words: [["be afraid of", "～を怖がる"], ["barking", "吠えている"], ["dogs", "犬"]] },
  { id: 278, en: `Do you know the lady standing on the corner?`, ja: `角に立っている女性を知っていますか？`, words: [["lady", "女性"], ["stand", "立つ"], ["corner", "角"], ["you", "あなた"]] },
  { id: 279, en: `The language used on the island is French.`, ja: `その島で使われている言語はフランス語です。`, words: [["language", "言語"], ["used", "使われている"], ["island", "島"], ["French", "フランス語"]] },
  { id: 280, en: `There are pieces of broken vase on the road.`, ja: `道路には壊れた花びんの破片がある。`, words: [["pieces", "破片・かけら"], ["broken", "壊れた"], ["vase", "花びん"], ["road", "道路"]] },
  { id: 281, en: `The blueberry field was separated by the stream a long time ago.`, ja: `ブルーベリー畑は、ずっと昔にその小川で分けられた。`, words: [["blueberry", "ブルーベリー"], ["field", "畑・野原"], ["separated", "分けられた"], ["stream", "小川"], ["a long time ago", "ずっと昔に"]] },
  { id: 282, en: `I want to take a trip, so could you lend me some money?`, ja: `私は旅行に行きたい、だから私にいくらかお金を貸してくれませんか？`, words: [["take a trip", "旅行に行く"], ["could you", "～してくれませんか"], ["lend", "貸す"], ["money", "お金"]] },
  { id: 283, en: `My grandfather recently suffered from a stomach disease.`, ja: `祖父は最近、胃の病気を患った。`, words: [["grandfather", "祖父"], ["recently", "最近"], ["suffer from", "～を患う"], ["stomach", "胃"], ["disease", "病気"]] },
  { id: 284, en: `She will probably invent various industrial robots in the future.`, ja: `彼女は将来、いろいろな工業ロボットを発明するだろう。`, words: [["probably", "たぶん"], ["invent", "発明する"], ["various", "いろいろな"], ["industrial", "工業の"], ["robots", "ロボット"]] },
  { id: 285, en: `I completely disagree with my wife on the policy.`, ja: `私はその政策で、妻とは完全に意見が異なる。`, words: [["completely", "完全に"], ["disagree with", "～と意見が異なる"], ["policy", "政策"], ["I", "私"]] },
  { id: 286, en: `I think he is brave rather than wise.`, ja: `私は、彼は賢いというよりも、むしろ勇敢だと思う。`, words: [["brave", "勇敢な"], ["rather than", "～よりむしろ"], ["wise", "賢い"], ["I", "私"], ["think", "思う"]] },
  { id: 287, en: `"What's the matter?" "Somebody stole my passport at the airport."`, ja: `「どうしたの？」「だれかが空港で私のパスポートを盗んだんだ」`, words: [["what's the matter", "どうしたの"], ["somebody", "だれか"], ["stole", "盗んだ（stealの過去形）"], ["passport", "パスポート"]] },
  { id: 288, en: `The fight over the issue destroyed the relationship among the directors.`, ja: `その問題に関する争いが、重役たちの関係を壊した。`, words: [["fight", "争い"], ["issue", "問題"], ["destroyed", "壊した"], ["relationship", "関係"], ["among", "～の間"], ["directors", "重役"]] },
  { id: 289, en: `She was kind enough to open the door for the kid.`, ja: `彼女は、子どもにドアを開けてあげるほど親切だった。`, words: [["kind", "親切な"], ["enough to", "～するほど"], ["open", "開ける"], ["door", "ドア"], ["kid", "子ども"]] },
  { id: 290, en: `She is too sleepy to notice the danger.`, ja: `彼女は眠すぎて、その危険性に気づかない。`, words: [["too...to", "～すぎて～できない"], ["sleepy", "眠い"], ["notice", "気づく"], ["danger", "危険"]] },
  { id: 291, en: `My toothache is so bad that I cannot go to the parade with my neighbors.`, ja: `私は歯痛がひどいので、近所の人とパレードに行くことができない。`, words: [["toothache", "歯痛"], ["so...that", "とても～なので"], ["parade", "パレード"], ["neighbors", "近所の人"]] },
  { id: 292, en: `I take part in this speech contest every year.`, ja: `私は毎年このスピーチコンテストに参加します。`, words: [["take part in", "～に参加する"], ["speech contest", "スピーチコンテスト"], ["every year", "毎年"], ["I", "私"], ["this", "この・これ"]] },
  { id: 293, en: `The decrease in the birth rate has caused serious damage to our community.`, ja: `出生率の低下は、私たちの地域社会に深刻な悪影響を引き起こしている。`, words: [["decrease", "低下・減少"], ["birth rate", "出生率"], ["cause", "引き起こす"], ["serious", "深刻な"], ["damage", "悪影響・損害"], ["community", "地域社会"]] },
  { id: 294, en: `The designer made a monument with this metal object.`, ja: `そのデザイナーは、この金属の物体で記念碑を作った。`, words: [["designer", "デザイナー"], ["monument", "記念碑"], ["metal", "金属"], ["object", "物体"]] },
  { id: 295, en: `Police officers protect citizens from terror.`, ja: `警察官は恐怖から市民を保護します。`, words: [["police officer", "警察官"], ["protect", "保護する"], ["citizens", "市民"], ["terror", "恐怖"]] },
  { id: 296, en: `The politician celebrated my success at business.`, ja: `その政治家は、私の仕事での成功をたたえた。`, words: [["politician", "政治家"], ["celebrated", "たたえた・祝った"], ["success", "成功"], ["business", "仕事・商売"]] },
  { id: 297, en: `We regarded her positive suggestion as helpful.`, ja: `私たちは、彼女の前向きな提案が有用だとみなした。`, words: [["regard A as B", "AをBとみなす"], ["positive", "前向きな"], ["suggestion", "提案"], ["helpful", "有用な"]] },
  { id: 298, en: `The bird in a cage was scared because it came toward a cat.`, ja: `猫が向かってきたので、かごの中の鳥はおびえた。`, words: [["bird", "鳥"], ["cage", "かご"], ["scared", "おびえた"], ["toward", "～に向かって"], ["cat", "猫"]] },
  { id: 299, en: `Most patients aren't disappointed by the successful dentist.`, ja: `ほとんどの患者は、その有能な歯科医にがっかりすることはない。`, words: [["most", "ほとんどの"], ["patients", "患者"], ["disappointed", "がっかりする"], ["successful", "有能な・成功した"], ["dentist", "歯科医"]] },
  { id: 300, en: `The owner doesn't allow the captain to reply in his rude way.`, ja: `オーナーは船長に、失礼な態度で返事をすることを許さない。`, words: [["owner", "オーナー"], ["allow A to", "Aが～するのを許す"], ["captain", "船長"], ["reply", "返事をする"], ["rude", "失礼な"], ["way", "態度・方法"]] },
];

// 全単語をフラットなリストに展開（例文情報を保持）
// key: 永続化（学習記録）用の一意キー
const WORDS = (() => {
  const list = [];
  for (const s of SENTENCES) {
    for (const [en, ja] of s.words) {
      list.push({ key: s.id + "|" + en, word: en, meaning: ja, sentEn: s.en, sentJa: s.ja, sentId: s.id, setIndex: 0 });
    }
  }
  return list;
})();

// 100語ごとにセットへ分割
const SET_SIZE = 100;
const SETS = (() => {
  const sets = [];
  for (let i = 0; i < WORDS.length; i += SET_SIZE) {
    sets.push(WORDS.slice(i, i + SET_SIZE));
  }
  return sets;
})();

// 各単語に所属セット番号を付与（SETS は WORDS の参照スライスなので同一オブジェクトを更新）
SETS.forEach((set, i) => set.forEach((w) => { w.setIndex = i; }));
